version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:80"
    environment:
      - MongoDbSettings__ConnectionString=${ATLAS_URI}
      - MongoDbSettings__DatabaseName=PhoneDirectoryDB